### ISSUE TITLE
Mac / iOS support

### ISSUE THREAD

**Issue by adamski** [ProjectPhysX/OpenCL-Wrapper#12]
It seems unclear if OpenCL is still supported on modern Apple platforms. 

Is it possible to use this library on macOS?

**Comment by ProjectPhysX** [comment]
Hi @adamski,

it works on macOS. Apple's M1/M2/M3 GPUs do support OpenCL and run it very performant/efficient actually, although Apple have deprecated OpenCL support. Quite ironic considering Apple invented OpenCL.
About iOS I'm not sure. I have no Apple devices to test.

Kind regards,
Moritz
