### ISSUE TITLE
Set Max Kernel Workgroup Size >256 (when Kernel includes Barrier)?

### ISSUE THREAD

**Issue by jonmdev** [ProjectPhysX/OpenCL-Wrapper#16]
I am still very much enjoying your project which has been fantastic. GPU's open up so many possibilities.

## Issue

Currently, I can test a kernel's max size via:

```
inline size_t get_kernel_max_workgroup_size(Device& device, Kernel& kernel) {
	//====================================================
	//CHECK KERNEL MAX WORKGROUP SIZE - with barrier in kernel, returns 256
	//====================================================
	size_t kernel_work_group_size;
	clGetKernelWorkGroupInfo(kernel.cl_kernel(), device.info.cl_device(), CL_KERNEL_WORK_GROUP_SIZE, sizeof(size_t), &kernel_work_group_size, NULL);
	return kernel_work_group_size;
}
```
Any Kernel that uses barrier, returns as 256 for this max workgroup size. This is expected as per the following:

>If you do not specify values for reqd_work_group_size and max_work_group_size, and the kernel contains a barrier, the offline compiler defaults to a maximum work-group size of 256 work-items. 
>
>https://www.intel.com/content/www/us/en/docs/programmable/683176/18-1/specifying-a-maximum-work-group-size.html

## Solutions?

One user suggests this can be overridden by the following approach:

>It turned out that what I was asking for is well possible, but requires a (seems undocumented) environment variable to be set. Namely if I set GPU_MAX_WORKGROUP_SIZE=1024 I can go up to that value, its even shown then in cl_info.
>
>https://community.amd.com/t5/opencl/running-opencl-work-groups-with-gt-256-elements/td-p/64264/1000

Or here the other approach is described with "attributes":

>One way to request this "larger than maximum workgroup size" is to call clEnqueueNDRangeKernel() with localWorkSize set to NULL (so that the runtime does not complain about the size being larger than the maximum workgroup size), but writing/compiling the kernel using __attribute__((reqd_work_group_size(X, Y, Z))), where X, Y, and Z make the total thread-count > 256. For instance, __attribute__((reqd_work_group_size(1024, 1, 1))).
>
>https://github.com/ROCm/ROCm/issues/330#issuecomment-367028224

## OpenCL Wrapper Approach?

That is the best information I can find on this subject. I am not sure how to do any of this in your system, though. How might one set the GPU_MAX_WORKGROUP_SIZE=1024? Or how would one add the attribute code to the kernel system? Where or how would I put it specifically?

Is there any working method in your system to allow this or would you suggest any approach that might work?

Thanks for any help as always.

**Comment by ProjectPhysX** [comment]
Hi @jonmdev,

- You can set the environment variable [here](https://github.com/ProjectPhysX/OpenCL-Wrapper/blob/master/src/opencl.hpp#L183) with
  ```c
  set_environment_variable((char*)"GPU_MAX_WORKGROUP_SIZE=1024");
  ```
- The attribute you can set [here](https://github.com/ProjectPhysX/OpenCL-Wrapper/blob/master/src/kernel.cpp#L6) with
  ```c
  __attribute__((reqd_work_group_size(1024, 1, 1))) kernel void add_kernel(global float* A, global float* B, global float* C) {
  	...
  }
  ```

Kind regards,
Moritz
