### ISSUE TITLE
Kernel Dimensions?

### ISSUE THREAD

**Issue by PJaramilloV** [ProjectPhysX/OpenCL-Wrapper#6]
I love what you did here in this Wrapper, it makes OpenCL's syntax so approachable. However i do find myself struggling to understand how to set up the Memory and Kernel like in plain OpenCL with global and local sizes in a {x, x} to interpret 2D data or {y,y,y} for 3D.

I know we can work around this by operating over the 1D index of get_global_(0), I've also noted that there are read and write methods like write_to_device_2d() but can't understand how to use them.

I would appreciate any clarification or help, many thanks again for this wrapper!

**Comment by ProjectPhysX** [comment]
Hi @PJaramilloV,

it's best to use a 1D range in OpenCL even for 2D/3D data. Use linear indexing then:
- 2D
  - kernel global range is `Nx*Ny`
  - ```c
    uint n = x+y*Nx;
     ```
  - ```c
    uint x = n%Nx;
    uint y = n/Nx;
     ```
- 3D
  - kernel global range is `Nx*Ny*Nz`
  - ```c
    uint n = x+(y+z*Ny)*Nx;
     ```
  - ```c
    uint x = (n%(Nx*Ny))%Nx;
    uint y = (n%(Nx*Ny))/Nx;
    uint z = n/(Nx*Ny);
     ```
With this you can go from the linear index `n` in the OpenCL kernel to `x`/`y`/(`z`) coordinates and be sure to have coalesced memory access. Note: keep in mind the maximum value of `uint`, `4294967295u`; if you have larger global range, use `ulong` instead for `n`.

The `write_to_device_2d()` etc. functions are there if you have a 1D array formatted in 2D through linear indexing, and you want to copy not the entire thing from CPU to GPU but only a small clipped 2D region. For copying the entire thing, `write_to_device()` is much faster.

Kind regards,
Moritz
