### ISSUE TITLE
Check kernel error status

### ISSUE THREAD

**Issue by danfrz** [ProjectPhysX/OpenCL-Wrapper#7]
Hello!

Thank you for your awesome project!

Forgive me if this isn't the right forum to ask this [possibly foolish] question, but is it possible to check kernel execution status with these helper scripts? I keep running in to "I run a kernel that modifies X memory and wait for this kernel to complete, I look at X memory and it is unmodified".

I assume my kernel is wrong in some way but it would be nice to get some feedback from OpenCL as to what happened.
Thanks.

**Comment by danfrz** [comment]
( I found the fix for my kernel, was calling with the wrong number of parameters, so in that case something like having availability to the return code from cl_queue.enqueueNDRangeKernel probably would be helpful )

**Comment by ProjectPhysX** [comment]
Hi @danfrz,

this is great feedback, thanks! I've now [added](https://github.com/ProjectPhysX/OpenCL-Wrapper/commit/4ca9815864104dabca11fffc417ecda4482e9b4d) checks for kernel error codes. These will at least tell you if the kernel name is misspelled or the number/size of kernel parameters is wrong. Only mismatching datatypes with same size, such as `Memory<float>` in C++ and `global int*` in OpenCL C can't be detected unfortunately.

Kind regards,
Moritz
