### ISSUE TITLE
Are you open source or not?

### ISSUE THREAD

**Issue by Tafnab** [ProjectPhysX/OpenCL-Wrapper#8]
Your license reads like open source, but the libs are only provided in binary form.  Want to clarify that?  I don't care either way.  But since I don't know you, I'd prefer to build my own libs.

**Comment by ProjectPhysX** [comment]
Yes, it's open-source. My license only excludes military use.

The OpenCL headers and the lib are from Khronos Group and provided as open-source. You can use your own lib if you prefer!
